version: "3.8"

services:
  app:
    build: .
    container_name: rubber_ducky_app
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./files:/app/files
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true
